# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - SitStayStyleGrooming

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      - name: npm install, build, and test
        run: |
          cd client
          npm install
          npm run build --if-present

      - name: List Files in Directory
        run: ls -R
        working-directory: ./client

      - name: Create ZIP Archives
        run: |
          zip -r client.zip ./ -x "./client/node_modules/*"

      - name: Upload artifact for deployment job - client
        uses: actions/upload-artifact@v3
        with:
          name: client-artifact
          path: client.zip

      - name: List Artifact Contents
        run: unzip -l client.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job - client
        uses: actions/download-artifact@v3
        with:
          name: client-artifact

      # Add the following steps to adjust npm permissions and configurations
      - name: Set npm prefix and install
        run: |
          npm install -g npm@10.2.3 --prefix ./client/node_modules
          npm cache clean -f
          chmod -R 755 ./client/node_modules
          npm install --package-lock-only
          npm ci

      - name: Set up Azure CLI
        uses: Azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENTID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENTSECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTIONID }}",
              "tenantId": "${{ secrets.AZURE_TENANTID }}"
            }

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SitStayStyleGrooming'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C1C16759A3734B5F88A9C39AC2BDDA09 }}
          package: client.zip

