# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - SitStayStyleGrooming

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd client
          npm install
          npm run build --if-present
          
      - name: Create ZIP Archives
        run: |
          cd client
          zip -r node_modules.zip node_modules
          zip -r public.zip public
          zip -r src.zip src
          zip package-lock.zip package-lock.json
          zip package.zip package.json

      - name: Upload artifact for deployment job - node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node-modules-artifact
          path: client/node_modules.zip

      - name: Upload artifact for deployment job - public
        uses: actions/upload-artifact@v2
        with:
          name: public-artifact
          path: client/public.zip

      - name: Upload artifact for deployment job - src
        uses: actions/upload-artifact@v2
        with:
          name: src-artifact
          path: client/src.zip

      - name: Upload artifact for deployment job - package-lock.json
        uses: actions/upload-artifact@v2
        with:
          name: package-lock-artifact
          path: client/package-lock.zip

      - name: Upload artifact for deployment job - package.json
        uses: actions/upload-artifact@v2
        with:
          name: package-artifact
          path: client/package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-modules-artifact public-artifact src-artifact package-lock-artifact package-artifact

      - name: Set up Azure CLI
        uses: Azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENTID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENTSECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTIONID }}",
              "tenantId": "${{ secrets.AZURE_TENANTID }}"
            }


      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SitStayStyleGrooming'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C1C16759A3734B5F88A9C39AC2BDDA09 }}
          package: ${{ runner.workspace }}/node-modules-artifact public-artifact src-artifact package-lock-artifact package-artifact
