name: Azure Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Change Directory and Install Dependencies
        run: |
          cd client
          npm install
          npm run build --if-present

      - name: Create ZIP Archive
        run: |
          zip -r node-app.zip client

      - name: Upload ZIP Archive
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app


      - name: Set up Azure CLI
        uses: Azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENTID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENTSECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTIONID }}",
              "tenantId": "${{ secrets.AZURE_TENANTID }}"
            }

      - name: Azure CLI Login
        run: az login

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SitStayStyle'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_3157d90e70ca465a88843876d8a2f449 }}
          package: ${{ runner.workspace }}/node-app.zip
